#!/usr/bin/env php
<?php
require_once (__DIR__ . "/vendor/autoload.php");

$loader = new Twig_Loader_Filesystem(__DIR__ . '/templates/');
$twig = new Twig_Environment($loader, array(
    'cache' => __DIR__ .'/cache/',
));
$twig->clearCacheFiles();

$f = new Twig_SimpleFunction("querify", function($data){
    $string = array();
    foreach ($data as $d) {
        $string[] = urlencode($d->key) . "=" .  urlencode($d->value);
    }
    return implode("&", $string);
});
$twig->addFunction("querify", $f);

$f = new Twig_SimpleFunction("prettify", function($data){
    return json_encode(json_decode($data), JSON_PRETTY_PRINT);
});
$twig->addFunction("prettify", $f);

/**
 * TODO Refactor
 * TODO if valid json - Format JSON (perhaps even with syntax highlighting if possible
 */
srand(1);

$env = array(
    "{{client_id}}" => sha1(rand()),
    "{{url}}" => "http://192.168.33.99",
);

$json = file_get_contents($argv[1]);
foreach($env as $key => $val) {
    $json = str_ireplace($key, $val, $json);
}
$c = json_decode($json);

mkdir(__DIR__ . '/output/requests',0777,true);


foreach($c->requests as $rkey => $request) {
    $relpath = "requests/" . str_ireplace(array('/','\\','.',' '),'_', $request->name) . ".html";
    $c->requests[$rkey]->page_path = $relpath;
    if (!count($request->responses)) {
        echo "Warning: No response examples for {$request->name}\n"; 
    }
    if (!$request->description) {
        echo "Warning: No response examples for {$request->name}\n"; 
    }
    file_put_contents(__DIR__ . "/output/" . $relpath , $twig->render('request.html', array("request" => $request)));
}

foreach ($c->folders as $folder) {
    foreach ($folder->order as $id) {
        foreach ($c->requests as $request) {
            if($request->id == $id) {
                $folder->requests[] = $request;
            }
        }
    }    
    $folders[] = $folder;
}

file_put_contents(__DIR__ . "/output/index.html", $twig->render('index.html', array("folders" => $folders)));
copy(__DIR__ . "/templates/styles.css",__DIR__ . "/output/styles.css");

?>