#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require_once __DIR__.'/vendor/autoload.php';
} elseif (file_exists(__DIR__.'/../../autoload.php')) {
    require_once __DIR__ . '/../../autoload.php';
}

require_once(__DIR__ . "/Command/GenerateCommand.php");

use Symfony\Component\Console\Application;

$console = new Application("Docodile", "0.2");

$console->addCommands(array(
    new GenerateCommand(),
));
$console->setDefaultCommand("generate");
$console->run();

?>
